// src/ai/flows/interactive-legal-guidance.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing interactive legal guidance to users in a chatbot mode.
 *
 * - interactiveLegalGuidance - An async function that takes a user's question as input and returns legal guidance.
 * - InteractiveLegalGuidanceInput - The input type for the interactiveLegalGuidance function (a string).
 * - InteractiveLegalGuidanceOutput - The return type for the interactiveLegalGuidance function (a string).
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const InteractiveLegalGuidanceInputSchema = z
  .string()
  .describe('The user question or statement.');
export type InteractiveLegalGuidanceInput = z.infer<
  typeof InteractiveLegalGuidanceInputSchema
>;

const InteractiveLegalGuidanceOutputSchema = z
  .string()
  .nullable()
  .optional()
  .describe('The legal guidance generated by the AI.');
export type InteractiveLegalGuidanceOutput = z.infer<
  typeof InteractiveLegalGuidanceOutputSchema
>;

export async function interactiveLegalGuidance(
  input: InteractiveLegalGuidanceInput
): Promise<InteractiveLegalGuidanceOutput> {
  return interactiveLegalGuidanceFlow(input);
}

const interactiveLegalGuidancePrompt = ai.definePrompt({
  name: 'interactiveLegalGuidancePrompt',
  input: {schema: InteractiveLegalGuidanceInputSchema},
  output: {schema: InteractiveLegalGuidanceOutputSchema},
  prompt: `You are an AI legal assistant. The user is interacting with you in a chatbot mode.

  Your job is to:
  Ask step-by-step questions to understand the legal problem, agreement, or concern.
  Always clarify missing details politely and logically, so the user feels guided and not interrogated.

  For any clause, section, or user concern, provide two explanations:
    a. In legal terms (short, precise, professional).
    b. In plain layman’s terms (easy to understand, everyday examples).

  For actions like signing a contract, identify pros and cons.
  List possible consequences (e.g., financial, legal, personal) in a balanced way, so the user can make an informed decision.
  Always warn the user if something looks risky or unfair.
  Always stay neutral, clear, and user-friendly.
  Emphasize "This is AI assistance, not a substitute for a licensed lawyer" at the end of advice.

  When responding, follow this structure:
  Document / Problem Summary
  Simplified Explanation (Layman Terms)
  Legal Explanation (Optional)
  Pros and Cons
  Consequences / Warnings
  Suggested Next Steps

  User Input: {{{$input}}}
  `,
});

const interactiveLegalGuidanceFlow = ai.defineFlow(
  {
    name: 'interactiveLegalGuidanceFlow',
    inputSchema: InteractiveLegalGuidanceInputSchema,
    outputSchema: InteractiveLegalGuidanceOutputSchema,
  },
  async input => {
    const {output} = await interactiveLegalGuidancePrompt(input);
    return output ?? '';
  }
);
