// src/ai/flows/interactive-legal-guidance.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing interactive legal guidance to users in a chatbot mode.
 *
 * - interactiveLegalGuidance - An async function that takes a user's question as input and returns legal guidance.
 * - InteractiveLegalGuidanceInput - The input type for the interactiveLegalGuidance function (a string).
 * - InteractiveLegalGuidanceOutput - The return type for the interactiveLegalGuidance function (a string).
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const InteractiveLegalGuidanceInputSchema = z
  .string()
  .describe('The user question or statement, potentially with document context.');
export type InteractiveLegalGuidanceInput = z.infer<
  typeof InteractiveLegalGuidanceInputSchema
>;

const InteractiveLegalGuidanceOutputSchema = z
  .string()
  .nullable()
  .describe('The legal guidance generated by the AI.');
export type InteractiveLegalGuidanceOutput = z.infer<
  typeof InteractiveLegalGuidanceOutputSchema
>;

export async function interactiveLegalGuidance(
  input: InteractiveLegalGuidanceInput
): Promise<InteractiveLegalGuidanceOutput> {
  return interactiveLegalGuidanceFlow(input);
}

const interactiveLegalGuidancePrompt = ai.definePrompt({
  name: 'interactiveLegalGuidancePrompt',
  input: {schema: InteractiveLegalGuidanceInputSchema},
  output: {schema: InteractiveLegalGuidanceOutputSchema},
  prompt: `You are an AI legal assistant. The user is asking for advice about a legal document they have provided. Your role is to help them understand it.

  Your job is to:
  1.  Carefully analyze the user's question to understand their core concern, even if it's phrased in simple, non-legal language (e.g., "is this safe to sign?").
  2.  Your answers MUST be based *only* on the provided document content. Do not invent information.
  3.  If the question is about a specific clause or action (like signing), provide a balanced view.
  4.  Always, always emphasize "This is AI assistance, not a substitute for a licensed lawyer" at the end of every response.

  When responding, follow this structure clearly:
  -   **Quick Answer:** Directly address the user's question based on the document (e.g., "Regarding your question about signing...").
  -   **Simplified Explanation:** Explain the relevant parts of the document in plain, easy-to-understand language. Use analogies if helpful.
  -   **Key Points & Warnings:** Highlight the most important clauses, risks, or consequences related to their question. If they ask if it's "safe," identify clauses that could be risky or unfair.
  -   **Disclaimer:** End with the mandatory disclaimer.

  Here is the full context of the user's request, which includes the document text and their specific question:
  {{{input}}}
  `,
});

const interactiveLegalGuidanceFlow = ai.defineFlow(
  {
    name: 'interactiveLegalGuidanceFlow',
    inputSchema: InteractiveLegalGuidanceInputSchema,
    outputSchema: InteractiveLegalGuidanceOutputSchema,
  },
  async input => {
    const {output} = await interactiveLegalGuidancePrompt(input);
    return output ?? '';
  }
);
