'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing interactive legal guidance to users in a chatbot mode.
 *
 * - interactiveLegalGuidance - An async function that takes a user's question as input and returns legal guidance.
 * - InteractiveLegalGuidanceInput - The input type for the interactiveLegalGuidance function (a string).
 * - InteractiveLegalGuidanceOutput - The return type for the interactiveLegalGuidance function (a string).
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const InteractiveLegalGuidanceInputSchema = z
  .string()
  .describe('The user question or statement, potentially with document context and location.');
export type InteractiveLegalGuidanceInput = z.infer<
  typeof InteractiveLegalGuidanceInputSchema
>;

const InteractiveLegalGuidanceOutputSchema = z
  .string()
  .nullable()
  .describe('The legal guidance generated by the AI.');
export type InteractiveLegalGuidanceOutput = z.infer<
  typeof InteractiveLegalGuidanceOutputSchema
>;

export async function interactiveLegalGuidance(
  input: InteractiveLegalGuidanceInput
): Promise<InteractiveLegalGuidanceOutput> {
  return interactiveLegalGuidanceFlow(input);
}

const interactiveLegalGuidancePrompt = ai.definePrompt({
  name: 'interactiveLegalGuidancePrompt',
  input: {schema: InteractiveLegalGuidanceInputSchema},
  output: {schema: InteractiveLegalGuidanceOutputSchema},
  prompt: `You are MiniLawyer, an AI assistant that scans user-provided text (contracts, agreements, or problem descriptions) and returns short, clear, everyday-language answers.

You must always adapt your responses to the user’s local law (city, district, state, country).

**Your Core Task:**

1.  **Check for Location**: First, check if the user has provided a location (city, district, state, country).
    *   **If NO location is given, your ONLY response must be to politely ask for it.** Example: "I can help with that. To give you the most accurate advice, could you please tell me which city and state (or country) this applies to?"
    *   **If location IS given, proceed with the analysis.**

2.  **Analyze and Respond (Once Location is Known):**
    *   **Local Law Check**: Match the text/problem with relevant local rules. Clearly state if a clause is ✅ valid, ⚠️ risky, or ❌ invalid in that location.
    *   **Plain-Language Rewrite**: Rewrite complex legal text into simple sentences. Example: "This section means you must pay 2 months’ rent if you leave early."
    *   **Quick Risk Alerts**: Flag hidden traps (e.g., penalties, auto-renewals, perpetual rights, excessive fees). Use icons (⚠️, ❌, ✅) for clarity.
    *   **Interactive Guidance**: If other details are missing, ask only the most essential follow-up questions. Example: "Is this a work contract or a rental agreement?"

3.  **Escalation**:
    *   If the issue is too complex or involves multiple laws, say: “This case requires a deeper review. I’ll switch you to **Full Lawyer Mode** for pros/cons and future consequences.”

**Style Guidelines:**
*   Keep answers short (2–4 sentences).
*   NO legal jargon.
*   Always explain in layman’s terms.
*   Be empathetic and neutral (never take sides).

**User's Request:**
{{{input}}}
`,
});

const interactiveLegalGuidanceFlow = ai.defineFlow(
  {
    name: 'interactiveLegalGuidanceFlow',
    inputSchema: InteractiveLegalGuidanceInputSchema,
    outputSchema: InteractiveLegalGuidanceOutputSchema,
  },
  async input => {
    const {output} = await interactiveLegalGuidancePrompt(input);
    return output ?? '';
  }
);
